extends RefCounted

## Generated by scripts/gen-shared-constants.mjs from the TS-side
## canonical values. Do NOT hand-edit; CI runs the generator and
## fails the lint job on any diff.
##
## physics.gd / movement.gd / player.gd alias their local consts
## from this file so a single edit in backend/shared/src/*.ts ratchets
## both sides.

# Mirrored from backend/shared/src/physics.ts
const HOVER_HEIGHT := 0.5
const JUMP_AMP := 2.0
const LEAP_JUMP_AMP := 7.0
const WALL_HEIGHT := 6.0
const JUMP_DURATION_S := 0.6
const BODY_VERTICAL_EXTENT := 1.4
const JUMP_COOLDOWN_S := 0.1
const BOUNCE_E_GROUNDED := 0.3
const BOUNCE_E_AERIAL := 0.7
const BOUNCE_E_WALL := 0.15

# Mirrored from backend/shared/src/movement.ts
const WALK_SPEED := 3.2
const SPRINT_SPEED := 5.6
const SURGE_SPEED_MULT := 1.5
const SURGE_DURATION_MS := 10000.0
const MAX_SPRINT := 100.0
const SPRINT_DRAIN_PER_S := 25.0
const SPRINT_REGEN_PER_S := 15.0
const SPRINT_ENGAGE_THRESHOLD := 20.0

# Mirrored from backend/shared/src/projectiles.ts
const PROJECTILE_RADIUS := 0.2
const SHOOT_COOLDOWN_MS := 1500.0

# Mirrored from backend/shared/src/names.ts
const NAME_ADJECTIVES := ["Silent", "Painted", "Loud", "Floppy", "Crooked", "Bashful", "Velvet", "Hushed", "Ruffled", "Striped", "Glossy", "Pale", "Sneaky", "Whiskered", "Brittle", "Tipsy", "Polka", "Wobbly", "Crinkled", "Powdered", "Squeaky", "Tufted", "Knobbly", "Frilly", "Wonky", "Boggled", "Plucky", "Drooping", "Frazzled", "Soggy", "Greasy", "Jaunty", "Saggy", "Lopsided", "Petite", "Stilted", "Drippy", "Mottled", "Googly", "Spangled", "Befuddled", "Twitchy", "Mournful", "Limpid", "Smudged", "Curdled", "Cracked", "Bumbling", "Threadbare", "Daffy", "Dusty", "Garish", "Hapless", "Wistful", "Brassy", "Maudlin", "Frumpy", "Yawning", "Stooped", "Vexed", "Spotty", "Lurching", "Foggy", "Crumbly", "Goofy", "Zany", "Wacky", "Kooky", "Loopy", "Nutty", "Bonkers", "Clumsy", "Giddy", "Madcap", "Cockeyed", "Harebrained", "Addled", "Ditzy", "Screwball", "Cuckoo", "Jumbled", "Galumphing", "Bamboozled", "Slapstick"]
const NAME_NOUNS := ["Bozo", "Coulrophobe", "Pierrot", "Harlequin", "Buffoon", "Jester", "Marceau", "Tramp", "Auguste", "Carnie", "Pagliacci", "Punchinello", "Hopo", "Cake", "Honk", "Greasepaint", "Stripes", "Tear", "Glove", "Wig", "Nose", "Shoe", "Banana", "Pinwheel", "Smile", "Frown", "Lapel", "Pocket", "Hatband", "Cravat", "Suspender", "Bowtie", "Trumpet", "Kazoo", "Squirt", "Ladder", "Bucket", "Pratfall", "Cartwheel", "Tightrope", "Unicycle", "Confetti", "Crumpet", "Boutonniere", "Mistletoe", "Marionette", "Glissando", "Pantomime", "Vaudeville", "Curtain", "Footlight", "Spotlight", "Soliloquy", "Pirouette", "Maskmaker", "Topiary", "Sashay", "Gambol", "Tumbler", "Patter", "Whoopee", "Mime", "Clown", "Zanni", "Pulcinella", "Brighella", "Colombina", "Pantalone", "Scaramuccia", "Dottore", "Capitano", "Innamorato", "Lazzo", "Burla", "Maschera", "Carnevale", "Tarantella", "Saltarello", "Serenata", "Gondola", "Pizzicato", "Cannoli", "Biscotto"]
