extends RefCounted

## Generated by scripts/gen-shared-constants.mjs from the TS-side
## canonical values. Do NOT hand-edit; CI runs the generator and
## fails the lint job on any diff.
##
## physics.gd / movement.gd / player.gd alias their local consts
## from this file so a single edit in backend/shared/src/*.ts ratchets
## both sides.

# Mirrored from backend/shared/src/physics.ts
const HOVER_HEIGHT := 0.5
const JUMP_AMP := 2.0
const JUMP_DURATION_S := 0.6
const BODY_VERTICAL_EXTENT := 1.4
const JUMP_COOLDOWN_S := 0.1
const BOUNCE_E_GROUNDED := 0.3
const BOUNCE_E_AERIAL := 0.7
const BOUNCE_E_WALL := 0.15

# Mirrored from backend/shared/src/movement.ts
const WALK_SPEED := 3.2
const SPRINT_SPEED := 5.6
const MAX_SPRINT := 100.0
const SPRINT_DRAIN_PER_S := 25.0
const SPRINT_REGEN_PER_S := 15.0
const SPRINT_ENGAGE_THRESHOLD := 20.0
