// Grid maze for every topology. Concentric rings made no sense on torus and
// Klein because an "open" sector on one side had no equivalent on the far
// side; rings on plane meanwhile didn't match the gridded look users
// associate with a labyrinth. One generator now drives every layout so the
// visual language is consistent.
//
// The maze is a spanning tree over an NxN grid of cells, generated by seeded
// randomized DFS.
//   - Plane: cells live inside a closed rectangle. Boundary edges are walls.
//   - Torus: cells wrap across both seams; boundary walls are skipped (the
//     topology folds both edges to the same line, so a boundary wall would
//     visually double up).
//   - Klein: same as torus but the x-seam flips the row index, matching the
//     Klein topology adapter.
//   - Sphere: 3x2 cube-face packing. Six independent 4x6 mazes share the
//     playfield; face boundaries carry no walls so a crossing player wraps
//     onto the adjacent face (see generateSphereGridWalls).
//
// Determinism: GDScript and TS must produce the same wall list for the same
// (seed, topology, gridN). Both use the same 32-bit LCG and traverse
// neighbors in the same fixed order, so the DFS path is identical.

import type { Topology } from './protocol.ts';
import { WORLD_WIDTH } from './topology.ts';
import type { WallSegment } from './labyrinth.ts';

export const GRID_MAZE_N = 10;

// Sphere cube-face layout. The playfield is packed as 3 face-columns by 2
// face-rows. Each face is its own 4x6 grid of square cells; total grid is
// therefore 12 wide x 12 tall, matching the per-face cell size (WORLD_WIDTH/12)
// in both axes.
export const SPHERE_FACE_COLS = 3;
export const SPHERE_FACE_ROWS = 2;
export const SPHERE_FACE_CELLS_X = 4;
export const SPHERE_FACE_CELLS_Z = 6;
export const SPHERE_GRID_X = SPHERE_FACE_COLS * SPHERE_FACE_CELLS_X; // 12
export const SPHERE_GRID_Z = SPHERE_FACE_ROWS * SPHERE_FACE_CELLS_Z; // 12

const DIR_EAST = 0;
const DIR_NORTH = 1;
const DIR_WEST = 2;
const DIR_SOUTH = 3;

interface Neighbor {
  cell: number;
  dir: number;
  crossesSeam: boolean;
}

export function generateGridMazeWalls(
  seed: number,
  topology: Topology,
  gridN: number = GRID_MAZE_N,
): WallSegment[] {
  if (topology === 'sphere') {
    return generateSphereGridWalls(seed);
  }
  if (topology === 'klein') {
    return generateKleinGridWalls(seed, gridN);
  }
  const total = gridN * gridN;
  const visited = new Uint8Array(total);
  // openings[cell] is a 4-bit mask: bit `dir` set means the wall in that
  // direction has been removed (the spanning tree linked cell to its
  // neighbor through that face).
  const openings = new Uint8Array(total);

  let rng = (seed | 0) >>> 0;
  const next = (): number => {
    rng = ((Math.imul(rng, 1664525) >>> 0) + 1013904223) >>> 0;
    return rng;
  };

  const start = next() % total;
  visited[start] = 1;
  const stack: number[] = [start];

  while (stack.length > 0) {
    const cur = stack[stack.length - 1]!;
    const candidates: Neighbor[] = [];
    for (let dir = 0; dir < 4; dir += 1) {
      const nb = neighborOf(cur, dir, gridN, topology);
      if (nb === null) continue;
      if (visited[nb.cell]) continue;
      candidates.push(nb);
    }
    if (candidates.length === 0) {
      stack.pop();
      continue;
    }
    const pick = candidates[next() % candidates.length]!;
    openings[cur] |= 1 << pick.dir;
    openings[pick.cell] |= 1 << oppositeDir(pick.dir);
    visited[pick.cell] = 1;
    stack.push(pick.cell);
  }

  braid(openings, gridN, topology, next);
  return emitWalls(openings, gridN, topology);
}

/**
 * Walk every cell that ended up with a single opening (a dead end) after the
 * spanning-tree DFS and knock one of its closed walls down. The result is a
 * braided maze: no terminal cells, multiple paths between most pairs of
 * cells, which is closer to a classical labyrinth pattern than the dead-end
 * mazes spanning trees produce.
 */
function braid(openings: Uint8Array, gridN: number, topology: Topology, next: () => number): void {
  const total = gridN * gridN;
  for (let cell = 0; cell < total; cell += 1) {
    if (popCountNibble(openings[cell]!) >= 2) continue;
    const closedNeighbors: { dir: number; cell: number }[] = [];
    for (let dir = 0; dir < 4; dir += 1) {
      if ((openings[cell]! & (1 << dir)) !== 0) continue;
      const nb = neighborOf(cell, dir, gridN, topology);
      if (nb === null) continue;
      closedNeighbors.push({ dir, cell: nb.cell });
    }
    if (closedNeighbors.length === 0) continue;
    const pick = closedNeighbors[next() % closedNeighbors.length]!;
    openings[cell] |= 1 << pick.dir;
    openings[pick.cell] |= 1 << oppositeDir(pick.dir);
  }
}

function popCountNibble(byte: number): number {
  let n = byte & 0xf;
  n = (n & 0x5) + ((n >> 1) & 0x5);
  n = (n & 0x3) + ((n >> 2) & 0x3);
  return n;
}

function oppositeDir(dir: number): number {
  return (dir + 2) % 4;
}

function neighborOf(cell: number, dir: number, gridN: number, topology: Topology): Neighbor | null {
  const cc = cell % gridN;
  const cr = Math.floor(cell / gridN);
  let nc = cc;
  let nr = cr;
  let crossesSeam = false;
  let flipRow = false;

  if (dir === DIR_EAST) nc = cc + 1;
  else if (dir === DIR_WEST) nc = cc - 1;
  else if (dir === DIR_NORTH) nr = cr + 1;
  else if (dir === DIR_SOUTH) nr = cr - 1;

  if (nc < 0 || nc >= gridN) {
    if (topology === 'plane') return null;
    nc = ((nc % gridN) + gridN) % gridN;
    crossesSeam = true;
    if (topology === 'klein') flipRow = true;
  }
  if (nr < 0 || nr >= gridN) {
    if (topology === 'plane') return null;
    nr = ((nr % gridN) + gridN) % gridN;
    crossesSeam = true;
  }
  if (flipRow) nr = gridN - 1 - nr;
  return { cell: nc + nr * gridN, dir, crossesSeam };
}

function emitWalls(openings: Uint8Array, gridN: number, topology: Topology): WallSegment[] {
  // For each cell, examine its EAST and NORTH faces. (South and west are
  // mirror images of the neighbor's north and east, so we only emit each
  // wall once.) If the face is closed and is not on a wrap seam, drop a wall
  // segment along it.
  const cell = WORLD_WIDTH / gridN;
  const half = WORLD_WIDTH / 2;
  const out: WallSegment[] = [];
  const closedBoundary = topology === 'plane';
  for (let r = 0; r < gridN; r += 1) {
    for (let c = 0; c < gridN; c += 1) {
      const id = c + r * gridN;
      const isLastCol = c === gridN - 1;
      const isLastRow = r === gridN - 1;
      const eastClosed = (openings[id]! & (1 << DIR_EAST)) === 0;
      const northClosed = (openings[id]! & (1 << DIR_NORTH)) === 0;
      // Plane keeps boundary walls (they are the playfield edge). Torus and
      // Klein drop them because the topology already folds both edges into
      // one and a wall would visually double up.
      if (eastClosed && (!isLastCol || closedBoundary)) {
        const x = (c + 1) * cell - half;
        const z0 = r * cell - half;
        const z1 = (r + 1) * cell - half;
        out.push({ ax: x, az: z0, bx: x, bz: z1 });
      }
      if (northClosed && (!isLastRow || closedBoundary)) {
        const z = (r + 1) * cell - half;
        const x0 = c * cell - half;
        const x1 = (c + 1) * cell - half;
        out.push({ ax: x0, az: z, bx: x1, bz: z });
      }
    }
  }
  // The east/north loop above can never emit the WEST or SOUTH boundary
  // walls of the playfield, since those have no cell to the west or south
  // to own them. Plane needs the full rectangle, so add them explicitly.
  if (closedBoundary) {
    for (let r = 0; r < gridN; r += 1) {
      const z0 = r * cell - half;
      const z1 = (r + 1) * cell - half;
      out.push({ ax: -half, az: z0, bx: -half, bz: z1 });
    }
    for (let c = 0; c < gridN; c += 1) {
      const x0 = c * cell - half;
      const x1 = (c + 1) * cell - half;
      out.push({ ax: x0, az: -half, bx: x1, bz: -half });
    }
  }
  return out;
}

/**
 * Klein bottle wall list as the double cover of a fundamental NxN klein maze.
 * The fundamental polygon (N x N cells, x-wrap flips the row index) is the
 * authoritative Klein bottle. To make the bottle's z-orientation flip
 * walkable space instead of an instantaneous teleport, we unfold that
 * fundamental into a 2N x N grid:
 *
 *   left half (cols 0..N-1): exact copy of the fundamental openings.
 *   right half (cols N..2N-1): z-mirror of the fundamental (flip the row
 *     index and swap NORTH<->SOUTH on each cell's mask).
 *
 * After unfolding the cell-to-cell openings line up at every seam:
 *   - the middle seam (x=0, between left col N-1 and right col N) matches
 *     the fundamental's east-wrap with flip;
 *   - the outer x seam (x=+-W, between cols 2N-1 and 0) is plain modular.
 *
 * So we emit the expanded 2N x N maze with torus-style wrap rules. The
 * walkable surface is a true Klein bottle; the player can walk through the
 * mirrored half before reaching the wrap, instead of seeing the world flip
 * at a single line.
 */
function generateKleinGridWalls(seed: number, gridN: number): WallSegment[] {
  // 1) Fundamental N x N maze with klein flip-row wrap, same as the
  // pre-double-cover behavior. Reuse the main DFS + braid through the
  // existing neighborOf path by calling with topology='klein'.
  const fundamental = buildFundamentalKleinOpenings(seed, gridN);

  // 2) Unfold into a 2N x N opening grid.
  const cols = 2 * gridN;
  const rows = gridN;
  const expanded = new Uint8Array(cols * rows);
  for (let r = 0; r < rows; r += 1) {
    for (let c = 0; c < gridN; c += 1) {
      // Left half: identity copy.
      expanded[c + r * cols] = fundamental[c + r * gridN]!;
      // Right half: z-mirror. Source row is N-1-r; NORTH<->SOUTH swap on
      // the mask since up/down are reversed in the mirrored copy. EAST and
      // WEST stay because the mirror is across z, not x.
      const src = fundamental[c + (rows - 1 - r) * gridN]!;
      expanded[gridN + c + r * cols] = swapNorthSouth(src);
    }
  }

  // 3) Emit walls for the 2N x N expanded grid. Torus rules: drop walls on
  // the outer boundaries (those identify with the opposite edges via plain
  // modular wrap), keep interior walls including the ones along the middle
  // seam at x=0 wherever they are closed in both adjacent cells.
  return emitKleinExpandedWalls(expanded, gridN);
}

function buildFundamentalKleinOpenings(seed: number, gridN: number): Uint8Array {
  const total = gridN * gridN;
  const visited = new Uint8Array(total);
  const openings = new Uint8Array(total);
  let rng = (seed | 0) >>> 0;
  const next = (): number => {
    rng = ((Math.imul(rng, 1664525) >>> 0) + 1013904223) >>> 0;
    return rng;
  };
  const start = next() % total;
  visited[start] = 1;
  const stack: number[] = [start];
  while (stack.length > 0) {
    const cur = stack[stack.length - 1]!;
    const candidates: Neighbor[] = [];
    for (let dir = 0; dir < 4; dir += 1) {
      const nb = neighborOf(cur, dir, gridN, 'klein');
      if (nb === null) continue;
      if (visited[nb.cell]) continue;
      candidates.push(nb);
    }
    if (candidates.length === 0) {
      stack.pop();
      continue;
    }
    const pick = candidates[next() % candidates.length]!;
    openings[cur] |= 1 << pick.dir;
    openings[pick.cell] |= 1 << oppositeDir(pick.dir);
    visited[pick.cell] = 1;
    stack.push(pick.cell);
  }
  braid(openings, gridN, 'klein', next);
  return openings;
}

function swapNorthSouth(mask: number): number {
  const east = mask & (1 << DIR_EAST);
  const north = mask & (1 << DIR_NORTH);
  const west = mask & (1 << DIR_WEST);
  const south = mask & (1 << DIR_SOUTH);
  return east | west | (north === 0 ? 0 : 1 << DIR_SOUTH) | (south === 0 ? 0 : 1 << DIR_NORTH);
}

function emitKleinExpandedWalls(openings: Uint8Array, gridN: number): WallSegment[] {
  const cols = 2 * gridN;
  const rows = gridN;
  const cell = WORLD_WIDTH / gridN;
  // The klein playfield spans x in [-WORLD_WIDTH, WORLD_WIDTH] (double cover)
  // and z in [-WORLD_WIDTH/2, WORLD_WIDTH/2]. Anchor walls accordingly.
  const halfX = WORLD_WIDTH;
  const halfZ = WORLD_WIDTH / 2;
  const out: WallSegment[] = [];
  for (let r = 0; r < rows; r += 1) {
    for (let c = 0; c < cols; c += 1) {
      const id = c + r * cols;
      const isLastCol = c === cols - 1;
      const isLastRow = r === rows - 1;
      const eastClosed = (openings[id]! & (1 << DIR_EAST)) === 0;
      const northClosed = (openings[id]! & (1 << DIR_NORTH)) === 0;
      // Klein wraps in both axes (modular on the 2N x N grid), so neither
      // outer boundary owns a wall.
      if (eastClosed && !isLastCol) {
        const x = (c + 1) * cell - halfX;
        const z0 = r * cell - halfZ;
        const z1 = (r + 1) * cell - halfZ;
        out.push({ ax: x, az: z0, bx: x, bz: z1 });
      }
      if (northClosed && !isLastRow) {
        const z = (r + 1) * cell - halfZ;
        const x0 = c * cell - halfX;
        const x1 = (c + 1) * cell - halfX;
        out.push({ ax: x0, az: z, bx: x1, bz: z });
      }
    }
  }
  return out;
}

/**
 * Sphere wall list: six independent grid mazes laid out 3x2 in the playfield.
 * Each face is a 4x6 cell grid. Face boundaries carry no walls so a player
 * crossing a face edge wraps onto the adjacent face via the topology adapter.
 *
 * The faces are visited in a fixed order (row 0 col 0, row 0 col 1, row 0
 * col 2, row 1 col 0, row 1 col 1, row 1 col 2) and share one LCG state, so
 * the generator is deterministic for a given seed and matches the GDScript
 * mirror in game/scripts/grid_maze.gd.
 *
 * TODO: this first cut uses torus-like wrapping between faces (modular 3x2),
 * which is not the rotated cube-net adjacency a true cube map needs. Proper
 * cube edge rotations and per-face spawn zones land in a follow-up.
 */
export function generateSphereGridWalls(seed: number): WallSegment[] {
  const fcx = SPHERE_FACE_CELLS_X;
  const fcz = SPHERE_FACE_CELLS_Z;
  const faceTotal = fcx * fcz;
  const totalCells = SPHERE_GRID_X * SPHERE_GRID_Z;
  // One opening byte per cell in the full 12x12 packing. Each face writes into
  // its own slice so the emit pass can iterate the full grid uniformly.
  const openings = new Uint8Array(totalCells);

  let rng = (seed | 0) >>> 0;
  const next = (): number => {
    rng = ((Math.imul(rng, 1664525) >>> 0) + 1013904223) >>> 0;
    return rng;
  };

  const localNeighbor = (localCell: number, dir: number): Neighbor | null => {
    const lc = localCell % fcx;
    const lr = Math.floor(localCell / fcx);
    let nc = lc;
    let nr = lr;
    if (dir === DIR_EAST) nc = lc + 1;
    else if (dir === DIR_WEST) nc = lc - 1;
    else if (dir === DIR_NORTH) nr = lr + 1;
    else if (dir === DIR_SOUTH) nr = lr - 1;
    if (nc < 0 || nc >= fcx) return null;
    if (nr < 0 || nr >= fcz) return null;
    return { cell: nc + nr * fcx, dir, crossesSeam: false };
  };

  // Iterate faces in the documented fixed order so GDScript and TS agree.
  for (let fr = 0; fr < SPHERE_FACE_ROWS; fr += 1) {
    for (let fc = 0; fc < SPHERE_FACE_COLS; fc += 1) {
      const localVisited = new Uint8Array(faceTotal);
      const localOpenings = new Uint8Array(faceTotal);

      const start = next() % faceTotal;
      localVisited[start] = 1;
      const stack: number[] = [start];
      while (stack.length > 0) {
        const cur = stack[stack.length - 1]!;
        const candidates: Neighbor[] = [];
        for (let dir = 0; dir < 4; dir += 1) {
          const nb = localNeighbor(cur, dir);
          if (nb === null) continue;
          if (localVisited[nb.cell]) continue;
          candidates.push(nb);
        }
        if (candidates.length === 0) {
          stack.pop();
          continue;
        }
        const pick = candidates[next() % candidates.length]!;
        localOpenings[cur] |= 1 << pick.dir;
        localOpenings[pick.cell] |= 1 << oppositeDir(pick.dir);
        localVisited[pick.cell] = 1;
        stack.push(pick.cell);
      }

      // Braid this face. Walks the local grid, knocks down one closed wall
      // per dead-end cell. The same shared LCG state advances through every
      // face's braid pass.
      for (let cell = 0; cell < faceTotal; cell += 1) {
        if (popCountNibble(localOpenings[cell]!) >= 2) continue;
        const closedNeighbors: { dir: number; cell: number }[] = [];
        for (let dir = 0; dir < 4; dir += 1) {
          if ((localOpenings[cell]! & (1 << dir)) !== 0) continue;
          const nb = localNeighbor(cell, dir);
          if (nb === null) continue;
          closedNeighbors.push({ dir, cell: nb.cell });
        }
        if (closedNeighbors.length === 0) continue;
        const pick = closedNeighbors[next() % closedNeighbors.length]!;
        localOpenings[cell] |= 1 << pick.dir;
        localOpenings[pick.cell] |= 1 << oppositeDir(pick.dir);
      }

      // Copy this face's openings into the global packing. Cell (lc, lr) in
      // face (fc, fr) lives at global column fc*fcx+lc, row fr*fcz+lr.
      for (let lr = 0; lr < fcz; lr += 1) {
        for (let lc = 0; lc < fcx; lc += 1) {
          const gc = fc * fcx + lc;
          const gr = fr * fcz + lr;
          openings[gc + gr * SPHERE_GRID_X] = localOpenings[lc + lr * fcx]!;
        }
      }
    }
  }

  return emitSphereWalls(openings);
}

function emitSphereWalls(openings: Uint8Array): WallSegment[] {
  const cell = WORLD_WIDTH / SPHERE_GRID_X;
  const half = WORLD_WIDTH / 2;
  const fcx = SPHERE_FACE_CELLS_X;
  const fcz = SPHERE_FACE_CELLS_Z;
  const out: WallSegment[] = [];
  for (let r = 0; r < SPHERE_GRID_Z; r += 1) {
    for (let c = 0; c < SPHERE_GRID_X; c += 1) {
      const id = c + r * SPHERE_GRID_X;
      const eastClosed = (openings[id]! & (1 << DIR_EAST)) === 0;
      const northClosed = (openings[id]! & (1 << DIR_NORTH)) === 0;
      // A face's east edge sits at local column index fcx-1. The wall east of
      // that cell is the face boundary, so it gets dropped. Same idea for the
      // north edge at local row fcz-1.
      const localCol = c % fcx;
      const localRow = r % fcz;
      const onFaceEastEdge = localCol === fcx - 1;
      const onFaceNorthEdge = localRow === fcz - 1;
      if (eastClosed && !onFaceEastEdge) {
        const x = (c + 1) * cell - half;
        const z0 = r * cell - half;
        const z1 = (r + 1) * cell - half;
        out.push({ ax: x, az: z0, bx: x, bz: z1 });
      }
      if (northClosed && !onFaceNorthEdge) {
        const z = (r + 1) * cell - half;
        const x0 = c * cell - half;
        const x1 = (c + 1) * cell - half;
        out.push({ ax: x0, az: z, bx: x1, bz: z });
      }
    }
  }
  return out;
}
