// Grid maze for every topology. Concentric rings made no sense on torus and
// Klein because an "open" sector on one side had no equivalent on the far
// side; rings on plane meanwhile didn't match the gridded look users
// associate with a labyrinth. One generator now drives every layout so the
// visual language is consistent.
//
// The maze is a spanning tree over an NxN grid of cells, generated by seeded
// randomized DFS.
//   - Plane: cells live inside a closed rectangle. Boundary edges are walls.
//   - Torus: cells wrap across both seams; boundary walls are skipped (the
//     topology folds both edges to the same line, so a boundary wall would
//     visually double up).
//   - Klein: same as torus but the x-seam flips the row index, matching the
//     Klein topology adapter.
//   - Genus-2 ("double torus"): cells are inscribed in the octagon's
//     bounding box; cells whose centres fall outside the polygon are
//     masked out and a DFS spanning tree runs only on the walkable cells
//     (see generateGenus2GridWalls). The octagon's boundary is the
//     identification seam itself, so no perimeter walls are emitted.
//
// Determinism: GDScript and TS must produce the same wall list for the same
// (seed, topology, gridN). Both use the same 32-bit LCG and traverse
// neighbors in the same fixed order, so the DFS path is identical.

import type { Topology } from './protocol.ts';
import { WORLD_WIDTH } from './topology.ts';
import type { WallSegment } from './labyrinth.ts';
import { OCTAGON_CIRCUMRADIUS, pointInOctagon } from './genus2.ts';
import { MOBIUS_HALF_X, MOBIUS_HALF_Z } from './mobius.ts';

export const GRID_MAZE_N = 10;

const DIR_EAST = 0;
const DIR_NORTH = 1;
const DIR_WEST = 2;
const DIR_SOUTH = 3;

interface Neighbor {
  cell: number;
  dir: number;
  crossesSeam: boolean;
}

export function generateGridMazeWalls(
  seed: number,
  topology: Topology,
  gridN: number = GRID_MAZE_N,
): WallSegment[] {
  if (topology === 'klein') {
    return generateKleinGridWalls(seed, gridN);
  }
  if (topology === 'genus2') {
    return generateGenus2GridWalls(seed);
  }
  if (topology === 'mobius') {
    return generateMobiusGridWalls(seed);
  }
  // Plane and torus share the rectangular grid path below.
  const total = gridN * gridN;
  const visited = new Uint8Array(total);
  // openings[cell] is a 4-bit mask: bit `dir` set means the wall in that
  // direction has been removed (the spanning tree linked cell to its
  // neighbor through that face).
  const openings = new Uint8Array(total);

  let rng = (seed | 0) >>> 0;
  const next = (): number => {
    rng = ((Math.imul(rng, 1664525) >>> 0) + 1013904223) >>> 0;
    return rng;
  };

  const start = next() % total;
  visited[start] = 1;
  const stack: number[] = [start];

  while (stack.length > 0) {
    const cur = stack[stack.length - 1]!;
    const candidates: Neighbor[] = [];
    for (let dir = 0; dir < 4; dir += 1) {
      const nb = neighborOf(cur, dir, gridN, topology);
      if (nb === null) continue;
      if (visited[nb.cell]) continue;
      candidates.push(nb);
    }
    if (candidates.length === 0) {
      stack.pop();
      continue;
    }
    const pick = candidates[next() % candidates.length]!;
    openings[cur] |= 1 << pick.dir;
    openings[pick.cell] |= 1 << oppositeDir(pick.dir);
    visited[pick.cell] = 1;
    stack.push(pick.cell);
  }

  braid(openings, gridN, topology, next);
  return emitWalls(openings, gridN, topology);
}

/**
 * Walk every cell that ended up with a single opening (a dead end) after the
 * spanning-tree DFS and knock one of its closed walls down. The result is a
 * braided maze: no terminal cells, multiple paths between most pairs of
 * cells, which is closer to a classical labyrinth pattern than the dead-end
 * mazes spanning trees produce.
 */
function braid(openings: Uint8Array, gridN: number, topology: Topology, next: () => number): void {
  const total = gridN * gridN;
  for (let cell = 0; cell < total; cell += 1) {
    if (popCountNibble(openings[cell]!) >= 2) continue;
    const closedNeighbors: { dir: number; cell: number }[] = [];
    for (let dir = 0; dir < 4; dir += 1) {
      if ((openings[cell]! & (1 << dir)) !== 0) continue;
      const nb = neighborOf(cell, dir, gridN, topology);
      if (nb === null) continue;
      closedNeighbors.push({ dir, cell: nb.cell });
    }
    if (closedNeighbors.length === 0) continue;
    const pick = closedNeighbors[next() % closedNeighbors.length]!;
    openings[cell] |= 1 << pick.dir;
    openings[pick.cell] |= 1 << oppositeDir(pick.dir);
  }
}

function popCountNibble(byte: number): number {
  let n = byte & 0xf;
  n = (n & 0x5) + ((n >> 1) & 0x5);
  n = (n & 0x3) + ((n >> 2) & 0x3);
  return n;
}

function oppositeDir(dir: number): number {
  return (dir + 2) % 4;
}

function neighborOf(cell: number, dir: number, gridN: number, topology: Topology): Neighbor | null {
  const cc = cell % gridN;
  const cr = Math.floor(cell / gridN);
  let nc = cc;
  let nr = cr;
  let crossesSeam = false;
  let flipRow = false;

  if (dir === DIR_EAST) nc = cc + 1;
  else if (dir === DIR_WEST) nc = cc - 1;
  else if (dir === DIR_NORTH) nr = cr + 1;
  else if (dir === DIR_SOUTH) nr = cr - 1;

  if (nc < 0 || nc >= gridN) {
    if (topology === 'plane') return null;
    nc = ((nc % gridN) + gridN) % gridN;
    crossesSeam = true;
    if (topology === 'klein') flipRow = true;
  }
  if (nr < 0 || nr >= gridN) {
    if (topology === 'plane') return null;
    nr = ((nr % gridN) + gridN) % gridN;
    crossesSeam = true;
  }
  if (flipRow) nr = gridN - 1 - nr;
  return { cell: nc + nr * gridN, dir, crossesSeam };
}

function emitWalls(openings: Uint8Array, gridN: number, topology: Topology): WallSegment[] {
  // For each cell, examine its EAST and NORTH faces. (South and west are
  // mirror images of the neighbor's north and east, so we only emit each
  // wall once.) If the face is closed and is not on a wrap seam, drop a wall
  // segment along it.
  const cell = WORLD_WIDTH / gridN;
  const half = WORLD_WIDTH / 2;
  const out: WallSegment[] = [];
  const closedBoundary = topology === 'plane';
  for (let r = 0; r < gridN; r += 1) {
    for (let c = 0; c < gridN; c += 1) {
      const id = c + r * gridN;
      const isLastCol = c === gridN - 1;
      const isLastRow = r === gridN - 1;
      const eastClosed = (openings[id]! & (1 << DIR_EAST)) === 0;
      const northClosed = (openings[id]! & (1 << DIR_NORTH)) === 0;
      // Plane keeps boundary walls (they are the playfield edge). Torus and
      // Klein drop them because the topology already folds both edges into
      // one and a wall would visually double up.
      if (eastClosed && (!isLastCol || closedBoundary)) {
        const x = (c + 1) * cell - half;
        const z0 = r * cell - half;
        const z1 = (r + 1) * cell - half;
        out.push({ ax: x, az: z0, bx: x, bz: z1 });
      }
      if (northClosed && (!isLastRow || closedBoundary)) {
        const z = (r + 1) * cell - half;
        const x0 = c * cell - half;
        const x1 = (c + 1) * cell - half;
        out.push({ ax: x0, az: z, bx: x1, bz: z });
      }
    }
  }
  // The east/north loop above can never emit the WEST or SOUTH boundary
  // walls of the playfield, since those have no cell to the west or south
  // to own them. Plane needs the full rectangle, so add them explicitly.
  if (closedBoundary) {
    for (let r = 0; r < gridN; r += 1) {
      const z0 = r * cell - half;
      const z1 = (r + 1) * cell - half;
      out.push({ ax: -half, az: z0, bx: -half, bz: z1 });
    }
    for (let c = 0; c < gridN; c += 1) {
      const x0 = c * cell - half;
      const x1 = (c + 1) * cell - half;
      out.push({ ax: x0, az: -half, bx: x1, bz: -half });
    }
  }
  return out;
}

/**
 * Klein bottle wall list as the double cover of a fundamental NxN klein maze.
 * The fundamental polygon (N x N cells, x-wrap flips the row index) is the
 * authoritative Klein bottle. To make the bottle's z-orientation flip
 * walkable space instead of an instantaneous teleport, we unfold that
 * fundamental into a 2N x N grid:
 *
 *   left half (cols 0..N-1): exact copy of the fundamental openings.
 *   right half (cols N..2N-1): z-mirror of the fundamental (flip the row
 *     index and swap NORTH<->SOUTH on each cell's mask).
 *
 * After unfolding the cell-to-cell openings line up at every seam:
 *   - the middle seam (x=0, between left col N-1 and right col N) matches
 *     the fundamental's east-wrap with flip;
 *   - the outer x seam (x=+-W, between cols 2N-1 and 0) is plain modular.
 *
 * So we emit the expanded 2N x N maze with torus-style wrap rules. The
 * walkable surface is a true Klein bottle; the player can walk through the
 * mirrored half before reaching the wrap, instead of seeing the world flip
 * at a single line.
 */
function generateKleinGridWalls(seed: number, gridN: number): WallSegment[] {
  // 1) Fundamental N x N maze with klein flip-row wrap, same as the
  // pre-double-cover behavior. Reuse the main DFS + braid through the
  // existing neighborOf path by calling with topology='klein'.
  const fundamental = buildFundamentalKleinOpenings(seed, gridN);

  // 2) Unfold into a 2N x N opening grid.
  const cols = 2 * gridN;
  const rows = gridN;
  const expanded = new Uint8Array(cols * rows);
  for (let r = 0; r < rows; r += 1) {
    for (let c = 0; c < gridN; c += 1) {
      // Left half: identity copy.
      expanded[c + r * cols] = fundamental[c + r * gridN]!;
      // Right half: z-mirror. Source row is N-1-r; NORTH<->SOUTH swap on
      // the mask since up/down are reversed in the mirrored copy. EAST and
      // WEST stay because the mirror is across z, not x.
      const src = fundamental[c + (rows - 1 - r) * gridN]!;
      expanded[gridN + c + r * cols] = swapNorthSouth(src);
    }
  }

  // 3) Emit walls for the 2N x N expanded grid. Torus rules: drop walls on
  // the outer boundaries (those identify with the opposite edges via plain
  // modular wrap), keep interior walls including the ones along the middle
  // seam at x=0 wherever they are closed in both adjacent cells.
  return emitKleinExpandedWalls(expanded, gridN);
}

function buildFundamentalKleinOpenings(seed: number, gridN: number): Uint8Array {
  const total = gridN * gridN;
  const visited = new Uint8Array(total);
  const openings = new Uint8Array(total);
  let rng = (seed | 0) >>> 0;
  const next = (): number => {
    rng = ((Math.imul(rng, 1664525) >>> 0) + 1013904223) >>> 0;
    return rng;
  };
  const start = next() % total;
  visited[start] = 1;
  const stack: number[] = [start];
  while (stack.length > 0) {
    const cur = stack[stack.length - 1]!;
    const candidates: Neighbor[] = [];
    for (let dir = 0; dir < 4; dir += 1) {
      const nb = neighborOf(cur, dir, gridN, 'klein');
      if (nb === null) continue;
      if (visited[nb.cell]) continue;
      candidates.push(nb);
    }
    if (candidates.length === 0) {
      stack.pop();
      continue;
    }
    const pick = candidates[next() % candidates.length]!;
    openings[cur] |= 1 << pick.dir;
    openings[pick.cell] |= 1 << oppositeDir(pick.dir);
    visited[pick.cell] = 1;
    stack.push(pick.cell);
  }
  braid(openings, gridN, 'klein', next);
  return openings;
}

function swapNorthSouth(mask: number): number {
  const east = mask & (1 << DIR_EAST);
  const north = mask & (1 << DIR_NORTH);
  const west = mask & (1 << DIR_WEST);
  const south = mask & (1 << DIR_SOUTH);
  return east | west | (north === 0 ? 0 : 1 << DIR_SOUTH) | (south === 0 ? 0 : 1 << DIR_NORTH);
}

function emitKleinExpandedWalls(openings: Uint8Array, gridN: number): WallSegment[] {
  const cols = 2 * gridN;
  const rows = gridN;
  const cell = WORLD_WIDTH / gridN;
  // The klein playfield spans x in [-WORLD_WIDTH, WORLD_WIDTH] (double cover)
  // and z in [-WORLD_WIDTH/2, WORLD_WIDTH/2]. Anchor walls accordingly.
  const halfX = WORLD_WIDTH;
  const halfZ = WORLD_WIDTH / 2;
  const out: WallSegment[] = [];
  for (let r = 0; r < rows; r += 1) {
    for (let c = 0; c < cols; c += 1) {
      const id = c + r * cols;
      const isLastCol = c === cols - 1;
      const isLastRow = r === rows - 1;
      const eastClosed = (openings[id]! & (1 << DIR_EAST)) === 0;
      const northClosed = (openings[id]! & (1 << DIR_NORTH)) === 0;
      // Klein wraps in both axes (modular on the 2N x N grid), so neither
      // outer boundary owns a wall.
      if (eastClosed && !isLastCol) {
        const x = (c + 1) * cell - halfX;
        const z0 = r * cell - halfZ;
        const z1 = (r + 1) * cell - halfZ;
        out.push({ ax: x, az: z0, bx: x, bz: z1 });
      }
      if (northClosed && !isLastRow) {
        const z = (r + 1) * cell - halfZ;
        const x0 = c * cell - halfX;
        const x1 = (c + 1) * cell - halfX;
        out.push({ ax: x0, az: z, bx: x1, bz: z });
      }
    }
  }
  return out;
}

/**
 * Maze cell count along each axis of the octagon's bounding box. Cells
 * are inscribed in the [-R, R] x [-R, R] bounding box; cells whose centres
 * fall outside the octagonal playfield are masked out (treated as
 * non-walkable, no maze edges emitted around them). The walkable cells
 * form an octagonal region of the grid.
 */
export const GENUS2_GRID_N = 12;

/**
 * Octagon maze. A square N x N grid is inscribed in the octagon's
 * bounding box. Cells whose centres fall inside the octagon are
 * walkable and participate in the DFS spanning tree; cells outside the
 * octagon are skipped. Edges between two walkable cells become maze
 * walls when the spanning tree didn't open them. The octagon's
 * boundary itself is an identification seam (no perimeter walls); cells
 * adjacent to the boundary just have one side open to the wrap.
 *
 * Faces visit order: top-to-bottom, left-to-right walkable cells under
 * the seed LCG, matching what the GDScript mirror does.
 */
export function generateGenus2GridWalls(seed: number): WallSegment[] {
  const N = GENUS2_GRID_N;
  const totalCells = N * N;
  const cellSize = (2 * OCTAGON_CIRCUMRADIUS) / N;
  const halfExt = OCTAGON_CIRCUMRADIUS;

  // Pre-compute which cells are walkable (centre inside the octagon).
  const walkable = new Uint8Array(totalCells);
  for (let r = 0; r < N; r += 1) {
    for (let c = 0; c < N; c += 1) {
      const cx = (c + 0.5) * cellSize - halfExt;
      const cz = (r + 0.5) * cellSize - halfExt;
      walkable[c + r * N] = pointInOctagon({ x: cx, z: cz }) ? 1 : 0;
    }
  }

  let rng = (seed | 0) >>> 0;
  const nextRand = (): number => {
    rng = ((Math.imul(rng, 1664525) >>> 0) + 1013904223) >>> 0;
    return rng;
  };

  const visited = new Uint8Array(totalCells);
  const openings = new Uint8Array(totalCells);

  const cellNeighbor = (cell: number, dir: number): number | null => {
    const cc = cell % N;
    const cr = Math.floor(cell / N);
    let nc = cc;
    let nr = cr;
    if (dir === DIR_EAST) nc = cc + 1;
    else if (dir === DIR_WEST) nc = cc - 1;
    else if (dir === DIR_NORTH) nr = cr + 1;
    else if (dir === DIR_SOUTH) nr = cr - 1;
    if (nc < 0 || nc >= N || nr < 0 || nr >= N) return null;
    const idx = nc + nr * N;
    return walkable[idx] ? idx : null;
  };

  // Start the DFS at the first walkable cell to keep the maze deterministic.
  let start = -1;
  for (let i = 0; i < totalCells; i += 1) {
    if (walkable[i]) {
      start = i;
      break;
    }
  }
  if (start < 0) return [];

  visited[start] = 1;
  const stack: number[] = [start];
  while (stack.length > 0) {
    const cur = stack[stack.length - 1]!;
    const candidates: number[] = [];
    for (let dir = 0; dir < 4; dir += 1) {
      const nb = cellNeighbor(cur, dir);
      if (nb === null) continue;
      if (visited[nb]) continue;
      candidates.push(dir);
    }
    if (candidates.length === 0) {
      stack.pop();
      continue;
    }
    const pickDir = candidates[nextRand() % candidates.length]!;
    const nb = cellNeighbor(cur, pickDir)!;
    openings[cur] |= 1 << pickDir;
    openings[nb] |= 1 << oppositeDir(pickDir);
    visited[nb] = 1;
    stack.push(nb);
  }

  // Braid: knock down one extra wall at each dead end so the maze loops.
  for (let cell = 0; cell < totalCells; cell += 1) {
    if (!walkable[cell]) continue;
    if (popCountNibble(openings[cell]!) >= 2) continue;
    const closedNeighbors: { dir: number; cell: number }[] = [];
    for (let dir = 0; dir < 4; dir += 1) {
      if ((openings[cell]! & (1 << dir)) !== 0) continue;
      const nb = cellNeighbor(cell, dir);
      if (nb === null) continue;
      closedNeighbors.push({ dir, cell: nb });
    }
    if (closedNeighbors.length === 0) continue;
    const pick = closedNeighbors[nextRand() % closedNeighbors.length]!;
    openings[cell] |= 1 << pick.dir;
    openings[pick.cell] |= 1 << oppositeDir(pick.dir);
  }

  // Emit walls between two walkable cells whose shared edge is closed.
  // The octagon boundary is an identification seam, so no perimeter walls.
  const out: WallSegment[] = [];
  for (let r = 0; r < N; r += 1) {
    for (let c = 0; c < N; c += 1) {
      const id = c + r * N;
      if (!walkable[id]) continue;
      const eastClosed = (openings[id]! & (1 << DIR_EAST)) === 0;
      const northClosed = (openings[id]! & (1 << DIR_NORTH)) === 0;
      const eastNbr = cellNeighbor(id, DIR_EAST);
      const northNbr = cellNeighbor(id, DIR_NORTH);
      if (eastClosed && eastNbr !== null) {
        const x = (c + 1) * cellSize - halfExt;
        const z0 = r * cellSize - halfExt;
        const z1 = (r + 1) * cellSize - halfExt;
        out.push({ ax: x, az: z0, bx: x, bz: z1 });
      }
      if (northClosed && northNbr !== null) {
        const z = (r + 1) * cellSize - halfExt;
        const x0 = c * cellSize - halfExt;
        const x1 = (c + 1) * cellSize - halfExt;
        out.push({ ax: x0, az: z, bx: x1, bz: z });
      }
    }
  }
  return out;
}

/**
 * Möbius strip grid sizing for the cylindrical double cover. The cover
 * is 2:1 in width:height; we use 2N x N cells (matching Klein). The
 * right half (cols >= N) is the z-mirror of the left half (cols < N)
 * so walking across the x = 0 fold sees continuous wall positions.
 */
export const MOBIUS_GRID_X = 2 * GRID_MAZE_N;
export const MOBIUS_GRID_Z = GRID_MAZE_N;

/**
 * Möbius strip maze rendered as the cylindrical double cover. Generates
 * a DFS spanning tree on the left half (cols 0..N-1) with x wrapping
 * pure-modular to itself, then mirrors the openings across z to fill
 * the right half (cols N..2N-1). x wraps modular at 2 * MOBIUS_HALF_X;
 * z is hard-bounded by top/bottom walls. The Möbius "twist" lives in
 * the z-mirror that fills the right half - walking from x = 0 into the
 * right half is the same as walking into the z-flipped image of the
 * left, exactly the Möbius identification (x, z) ~ (x + L, -z).
 */
export function generateMobiusGridWalls(seed: number): WallSegment[] {
  const cols = MOBIUS_GRID_X;
  const rows = MOBIUS_GRID_Z;
  const fundamentalCols = cols / 2; // = N, the left-half count
  const total = cols * rows;
  const cellSize = (2 * MOBIUS_HALF_X) / cols;
  const halfX = MOBIUS_HALF_X;
  const halfZ = MOBIUS_HALF_Z;

  let rng = (seed | 0) >>> 0;
  const nextRand = (): number => {
    rng = ((Math.imul(rng, 1664525) >>> 0) + 1013904223) >>> 0;
    return rng;
  };

  // Build the fundamental-half maze: DFS over the left N cols, treating
  // the left and right ends of this half as a torus seam (x wraps pure
  // modular within the fundamental). z is hard-bounded.
  const fundamentalNeighbor = (cell: number, dir: number): { cell: number; dir: number } | null => {
    const cc = cell % fundamentalCols;
    const cr = Math.floor(cell / fundamentalCols);
    let nc = cc;
    let nr = cr;
    if (dir === DIR_EAST) nc = cc + 1;
    else if (dir === DIR_WEST) nc = cc - 1;
    else if (dir === DIR_NORTH) nr = cr + 1;
    else if (dir === DIR_SOUTH) nr = cr - 1;
    if (nc < 0 || nc >= fundamentalCols)
      nc = ((nc % fundamentalCols) + fundamentalCols) % fundamentalCols;
    if (nr < 0 || nr >= rows) return null;
    return { cell: nc + nr * fundamentalCols, dir };
  };
  const fundamentalOpenings = new Uint8Array(fundamentalCols * rows);
  const fundamentalVisited = new Uint8Array(fundamentalCols * rows);
  const start = nextRand() % (fundamentalCols * rows);
  fundamentalVisited[start] = 1;
  const stack: number[] = [start];
  while (stack.length > 0) {
    const cur = stack[stack.length - 1]!;
    const candidates: { cell: number; dir: number }[] = [];
    for (let dir = 0; dir < 4; dir += 1) {
      const nb = fundamentalNeighbor(cur, dir);
      if (nb === null) continue;
      if (fundamentalVisited[nb.cell]) continue;
      candidates.push(nb);
    }
    if (candidates.length === 0) {
      stack.pop();
      continue;
    }
    const pick = candidates[nextRand() % candidates.length]!;
    fundamentalOpenings[cur] |= 1 << pick.dir;
    fundamentalOpenings[pick.cell] |= 1 << oppositeDir(pick.dir);
    fundamentalVisited[pick.cell] = 1;
    stack.push(pick.cell);
  }
  for (let cell = 0; cell < fundamentalCols * rows; cell += 1) {
    if (popCountNibble(fundamentalOpenings[cell]!) >= 2) continue;
    const closed: { dir: number; cell: number }[] = [];
    for (let dir = 0; dir < 4; dir += 1) {
      if ((fundamentalOpenings[cell]! & (1 << dir)) !== 0) continue;
      const nb = fundamentalNeighbor(cell, dir);
      if (nb === null) continue;
      closed.push({ dir, cell: nb.cell });
    }
    if (closed.length === 0) continue;
    const pick = closed[nextRand() % closed.length]!;
    fundamentalOpenings[cell] |= 1 << pick.dir;
    fundamentalOpenings[pick.cell] |= 1 << oppositeDir(pick.dir);
  }

  // Expand to the double cover: left half = fundamental, right half =
  // z-mirror of fundamental. The mirror swaps north <-> south openings.
  const openings = new Uint8Array(total);
  for (let r = 0; r < rows; r += 1) {
    for (let c = 0; c < fundamentalCols; c += 1) {
      openings[c + r * cols] = fundamentalOpenings[c + r * fundamentalCols]!;
    }
    for (let c = 0; c < fundamentalCols; c += 1) {
      const mirroredR = rows - 1 - r;
      const fundOpening = fundamentalOpenings[c + r * fundamentalCols]!;
      openings[c + fundamentalCols + mirroredR * cols] = swapNorthSouth(fundOpening);
    }
  }

  // Emit walls. East/north of each cell; skip the right-edge seam (last
  // col's east is the x wrap, open). Add hard top/bottom walls explicitly.
  const out: WallSegment[] = [];
  for (let r = 0; r < rows; r += 1) {
    for (let c = 0; c < cols; c += 1) {
      const id = c + r * cols;
      const eastClosed = (openings[id]! & (1 << DIR_EAST)) === 0;
      const northClosed = (openings[id]! & (1 << DIR_NORTH)) === 0;
      const isLastCol = c === cols - 1;
      const isLastRow = r === rows - 1;
      if (eastClosed && !isLastCol) {
        const x = (c + 1) * cellSize - halfX;
        const z0 = r * cellSize - halfZ;
        const z1 = (r + 1) * cellSize - halfZ;
        out.push({ ax: x, az: z0, bx: x, bz: z1 });
      }
      if (northClosed && !isLastRow) {
        const z = (r + 1) * cellSize - halfZ;
        const x0 = c * cellSize - halfX;
        const x1 = (c + 1) * cellSize - halfX;
        out.push({ ax: x0, az: z, bx: x1, bz: z });
      }
    }
  }
  for (let c = 0; c < cols; c += 1) {
    const x0 = c * cellSize - halfX;
    const x1 = (c + 1) * cellSize - halfX;
    out.push({ ax: x0, az: halfZ, bx: x1, bz: halfZ });
    out.push({ ax: x0, az: -halfZ, bx: x1, bz: -halfZ });
  }
  return out;
}
