// Grid maze for every topology. Concentric rings made no sense on torus and
// Klein because an "open" sector on one side had no equivalent on the far
// side; rings on plane meanwhile didn't match the gridded look users
// associate with a labyrinth. One generator now drives all three layouts so
// the visual language is consistent.
//
// The maze is a spanning tree over an NxN grid of cells, generated by seeded
// randomized DFS.
//   - Plane: cells live inside a closed rectangle. Boundary edges are walls.
//   - Torus: cells wrap across both seams; boundary walls are skipped (the
//     topology folds both edges to the same line, so a boundary wall would
//     visually double up).
//   - Klein: same as torus but the x-seam flips the row index, matching the
//     Klein topology adapter.
//
// Determinism: GDScript and TS must produce the same wall list for the same
// (seed, topology, gridN). Both use the same 32-bit LCG and traverse
// neighbors in the same fixed order, so the DFS path is identical.

import type { Topology } from './protocol.ts';
import { WORLD_WIDTH } from './topology.ts';
import type { WallSegment } from './labyrinth.ts';

export const GRID_MAZE_N = 10;

const DIR_EAST = 0;
const DIR_NORTH = 1;
const DIR_WEST = 2;
const DIR_SOUTH = 3;

interface Neighbor {
  cell: number;
  dir: number;
  crossesSeam: boolean;
}

export function generateGridMazeWalls(
  seed: number,
  topology: Topology,
  gridN: number = GRID_MAZE_N,
): WallSegment[] {
  if (topology === 'sphere') {
    // Sphere still uses the legacy concentric-ring layout pending a real
    // cube-mapped topology. Callers fall back to ring generation when this
    // returns an empty list.
    return [];
  }
  const total = gridN * gridN;
  const visited = new Uint8Array(total);
  // openings[cell] is a 4-bit mask: bit `dir` set means the wall in that
  // direction has been removed (the spanning tree linked cell to its
  // neighbor through that face).
  const openings = new Uint8Array(total);

  let rng = (seed | 0) >>> 0;
  const next = (): number => {
    rng = ((Math.imul(rng, 1664525) >>> 0) + 1013904223) >>> 0;
    return rng;
  };

  const start = next() % total;
  visited[start] = 1;
  const stack: number[] = [start];

  while (stack.length > 0) {
    const cur = stack[stack.length - 1]!;
    const candidates: Neighbor[] = [];
    for (let dir = 0; dir < 4; dir += 1) {
      const nb = neighborOf(cur, dir, gridN, topology);
      if (nb === null) continue;
      if (visited[nb.cell]) continue;
      candidates.push(nb);
    }
    if (candidates.length === 0) {
      stack.pop();
      continue;
    }
    const pick = candidates[next() % candidates.length]!;
    openings[cur] |= 1 << pick.dir;
    openings[pick.cell] |= 1 << oppositeDir(pick.dir);
    visited[pick.cell] = 1;
    stack.push(pick.cell);
  }

  braid(openings, gridN, topology, next);
  return emitWalls(openings, gridN, topology);
}

/**
 * Walk every cell that ended up with a single opening (a dead end) after the
 * spanning-tree DFS and knock one of its closed walls down. The result is a
 * braided maze: no terminal cells, multiple paths between most pairs of
 * cells, which is closer to a classical labyrinth pattern than the dead-end
 * mazes spanning trees produce.
 */
function braid(openings: Uint8Array, gridN: number, topology: Topology, next: () => number): void {
  const total = gridN * gridN;
  for (let cell = 0; cell < total; cell += 1) {
    if (popCountNibble(openings[cell]!) >= 2) continue;
    const closedNeighbors: { dir: number; cell: number }[] = [];
    for (let dir = 0; dir < 4; dir += 1) {
      if ((openings[cell]! & (1 << dir)) !== 0) continue;
      const nb = neighborOf(cell, dir, gridN, topology);
      if (nb === null) continue;
      closedNeighbors.push({ dir, cell: nb.cell });
    }
    if (closedNeighbors.length === 0) continue;
    const pick = closedNeighbors[next() % closedNeighbors.length]!;
    openings[cell] |= 1 << pick.dir;
    openings[pick.cell] |= 1 << oppositeDir(pick.dir);
  }
}

function popCountNibble(byte: number): number {
  let n = byte & 0xf;
  n = (n & 0x5) + ((n >> 1) & 0x5);
  n = (n & 0x3) + ((n >> 2) & 0x3);
  return n;
}

function oppositeDir(dir: number): number {
  return (dir + 2) % 4;
}

function neighborOf(cell: number, dir: number, gridN: number, topology: Topology): Neighbor | null {
  const cc = cell % gridN;
  const cr = Math.floor(cell / gridN);
  let nc = cc;
  let nr = cr;
  let crossesSeam = false;
  let flipRow = false;

  if (dir === DIR_EAST) nc = cc + 1;
  else if (dir === DIR_WEST) nc = cc - 1;
  else if (dir === DIR_NORTH) nr = cr + 1;
  else if (dir === DIR_SOUTH) nr = cr - 1;

  if (nc < 0 || nc >= gridN) {
    if (topology === 'plane') return null;
    nc = ((nc % gridN) + gridN) % gridN;
    crossesSeam = true;
    if (topology === 'klein') flipRow = true;
  }
  if (nr < 0 || nr >= gridN) {
    if (topology === 'plane') return null;
    nr = ((nr % gridN) + gridN) % gridN;
    crossesSeam = true;
  }
  if (flipRow) nr = gridN - 1 - nr;
  return { cell: nc + nr * gridN, dir, crossesSeam };
}

function emitWalls(openings: Uint8Array, gridN: number, topology: Topology): WallSegment[] {
  // For each cell, examine its EAST and NORTH faces. (South and west are
  // mirror images of the neighbor's north and east, so we only emit each
  // wall once.) If the face is closed and is not on a wrap seam, drop a wall
  // segment along it.
  const cell = WORLD_WIDTH / gridN;
  const half = WORLD_WIDTH / 2;
  const out: WallSegment[] = [];
  const closedBoundary = topology === 'plane';
  for (let r = 0; r < gridN; r += 1) {
    for (let c = 0; c < gridN; c += 1) {
      const id = c + r * gridN;
      const isLastCol = c === gridN - 1;
      const isLastRow = r === gridN - 1;
      const eastClosed = (openings[id]! & (1 << DIR_EAST)) === 0;
      const northClosed = (openings[id]! & (1 << DIR_NORTH)) === 0;
      // Plane keeps boundary walls (they are the playfield edge). Torus and
      // Klein drop them because the topology already folds both edges into
      // one and a wall would visually double up.
      if (eastClosed && (!isLastCol || closedBoundary)) {
        const x = (c + 1) * cell - half;
        const z0 = r * cell - half;
        const z1 = (r + 1) * cell - half;
        out.push({ ax: x, az: z0, bx: x, bz: z1 });
      }
      if (northClosed && (!isLastRow || closedBoundary)) {
        const z = (r + 1) * cell - half;
        const x0 = c * cell - half;
        const x1 = (c + 1) * cell - half;
        out.push({ ax: x0, az: z, bx: x1, bz: z });
      }
    }
  }
  // The east/north loop above can never emit the WEST or SOUTH boundary
  // walls of the playfield, since those have no cell to the west or south
  // to own them. Plane needs the full rectangle, so add them explicitly.
  if (closedBoundary) {
    for (let r = 0; r < gridN; r += 1) {
      const z0 = r * cell - half;
      const z1 = (r + 1) * cell - half;
      out.push({ ax: -half, az: z0, bx: -half, bz: z1 });
    }
    for (let c = 0; c < gridN; c += 1) {
      const x0 = c * cell - half;
      const x1 = (c + 1) * cell - half;
      out.push({ ax: x0, az: -half, bx: x1, bz: -half });
    }
  }
  return out;
}
