// Canonical clown/mime name word lists. Single source of truth shared by the
// server bot-name generator (botManager.ts) and, via
// scripts/gen-shared-constants.mjs, the GDScript client generator
// (username_generator.gd). Edit the lists here only; CI regenerates
// shared_constants.gd and fails on drift.

export const NAME_ADJECTIVES = [
  'Silent',
  'Painted',
  'Loud',
  'Floppy',
  'Crooked',
  'Bashful',
  'Velvet',
  'Hushed',
  'Ruffled',
  'Striped',
  'Glossy',
  'Pale',
  'Sneaky',
  'Whiskered',
  'Brittle',
  'Tipsy',
  'Polka',
  'Wobbly',
  'Crinkled',
  'Powdered',
  'Squeaky',
  'Tufted',
  'Knobbly',
  'Frilly',
  'Wonky',
  'Boggled',
  'Plucky',
  'Drooping',
  'Frazzled',
  'Soggy',
  'Greasy',
  'Jaunty',
  'Saggy',
  'Lopsided',
  'Petite',
  'Stilted',
  'Drippy',
  'Mottled',
  'Googly',
  'Spangled',
  'Befuddled',
  'Twitchy',
  'Mournful',
  'Limpid',
  'Smudged',
  'Curdled',
  'Cracked',
  'Bumbling',
  'Threadbare',
  'Daffy',
  'Dusty',
  'Garish',
  'Hapless',
  'Wistful',
  'Brassy',
  'Maudlin',
  'Frumpy',
  'Yawning',
  'Stooped',
  'Vexed',
  'Spotty',
  'Lurching',
  'Foggy',
  'Crumbly',
  'Goofy',
  'Zany',
  'Wacky',
  'Kooky',
  'Loopy',
  'Nutty',
  'Bonkers',
  'Clumsy',
  'Giddy',
  'Madcap',
  'Cockeyed',
  'Harebrained',
  'Addled',
  'Ditzy',
  'Screwball',
  'Cuckoo',
  'Jumbled',
  'Galumphing',
  'Bamboozled',
  'Slapstick',
];

export const NAME_NOUNS = [
  'Bozo',
  'Coulrophobe',
  'Pierrot',
  'Harlequin',
  'Buffoon',
  'Jester',
  'Marceau',
  'Tramp',
  'Auguste',
  'Carnie',
  'Pagliacci',
  'Punchinello',
  'Hopo',
  'Cake',
  'Honk',
  'Greasepaint',
  'Stripes',
  'Tear',
  'Glove',
  'Wig',
  'Nose',
  'Shoe',
  'Banana',
  'Pinwheel',
  'Smile',
  'Frown',
  'Lapel',
  'Pocket',
  'Hatband',
  'Cravat',
  'Suspender',
  'Bowtie',
  'Trumpet',
  'Kazoo',
  'Squirt',
  'Ladder',
  'Bucket',
  'Pratfall',
  'Cartwheel',
  'Tightrope',
  'Unicycle',
  'Confetti',
  'Crumpet',
  'Boutonniere',
  'Mistletoe',
  'Marionette',
  'Glissando',
  'Pantomime',
  'Vaudeville',
  'Curtain',
  'Footlight',
  'Spotlight',
  'Soliloquy',
  'Pirouette',
  'Maskmaker',
  'Topiary',
  'Sashay',
  'Gambol',
  'Tumbler',
  'Patter',
  'Whoopee',
  'Mime',
  'Clown',
  'Zanni',
  'Pulcinella',
  'Brighella',
  'Colombina',
  'Pantalone',
  'Scaramuccia',
  'Dottore',
  'Capitano',
  'Innamorato',
  'Lazzo',
  'Burla',
  'Maschera',
  'Carnevale',
  'Tarantella',
  'Saltarello',
  'Serenata',
  'Gondola',
  'Pizzicato',
  'Cannoli',
  'Biscotto',
];

// Pairs a random adjective + noun + 3-digit suffix, e.g. "SilentBozo042".
// The GDScript client mirrors this shape with its own RNG; only the word
// lists are shared, not this function.
export function generateRandomName(): string {
  const adj = NAME_ADJECTIVES[Math.floor(Math.random() * NAME_ADJECTIVES.length)]!;
  const noun = NAME_NOUNS[Math.floor(Math.random() * NAME_NOUNS.length)]!;
  const num = Math.floor(Math.random() * 1000)
    .toString()
    .padStart(3, '0');
  return `${adj}${noun}${num}`;
}
